name: Nick
favicon: null
layout_spectrum: 0.27001
typography_spectrum: 0.77989
title: Daily Nick
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbbdb1'
    - '#b5a396'
    - '#447589'
    - '#668c9a'
    - '#3c3a42'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
